const resList = [
  {
    restaurantName: "KFC",
    location: "Various Locations",
    categories: ["Chicken", "Burgers", "Sides", "Beverages"],
    item: {
      id: 1,
      name: "Original Recipe Chicken",
      description: "Fried chicken with a secret blend of 11 herbs and spices.",
      price: 299,
      imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/4a509cf1-ea35-497b-9813-59145c5007c9_588619.JPG",
      category: "Chicken",
      rating: 4.5,
    },
    averageRating: 4.4,
    deliveryTime: "30-40 mins",
  },
  {
    restaurantName: "Burger King",
    location: "Various Locations",
    categories: ["Burgers", "Sides", "Beverages"],
    item: {
      id: 2,
      name: "Whopper",
      description: "Flame-grilled beef patty topped with fresh vegetables.",
      price: 249,
      category: "Burgers",
      imageUrl: "https://b.zmtcdn.com/data/pictures/chains/8/18902548/c8008523810583087401ff292c1763a3.jpg?fit=around|750:500&crop=750:500;*,*",
      rating: 4.6,
    },
    averageRating: 4.5,
    deliveryTime: "30-45 mins",
  },
  {
    restaurantName: "Domino's Pizza",
    location: "Various Locations",
    categories: ["Pizzas", "Sides", "Desserts"],
    item: {
      id: 3,
      name: "Margherita Pizza",
      description: "Classic pizza topped with mozzarella cheese and basil.",
      price: 499,
      category: "Pizzas",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwTMdjFNfvW3Q7t_0U4kCGi9NjC0bnODoGmA&s",
      rating: 4.7,
    },
    averageRating: 4.6,
    deliveryTime: "25-35 mins",
  },
  {
    restaurantName: "Pizza Hut",
    location: "Various Locations",
    categories: ["Pizzas", "Pasta", "Sides", "Desserts"],
    item: {
      id: 4,
      name: "Pepperoni Pizza",
      description: "Classic pizza topped with spicy pepperoni and mozzarella.",
      price: 599,
      imageUrl: "https://th.bing.com/th/id/OIP.d7bzyca2w6dq1DYB1uzUYQAAAA?w=265&h=180&c=7&r=0&o=5&pid=1.7",
      category: "Pizzas",
      rating: 4.8,
    },
    averageRating: 4.7,
    deliveryTime: "30-40 mins",
  },
  {
    restaurantName: "Taco Bell",
    location: "Various Locations",
    categories: ["Tacos", "Burritos", "Sides", "Drinks"],
    item: {
      id: 5,
      name: "Crunchy Tacos",
      description: "Crispy taco shells filled with seasoned beef and fresh toppings.",
      price: 199,
      category: "Tacos",
      imageUrl: "https://th.bing.com/th/id/OIP.pPIAhBhvBUuXluLJHCETHAHaE8?w=236&h=180&c=7&r=0&o=5&pid=1.7",
      rating: 4.4,
    },
    averageRating: 4.3,
    deliveryTime: "20-30 mins",
  },
  {
    restaurantName: "Subway",
    location: "Various Locations",
    categories: ["Sandwiches", "Salads", "Wraps"],
    item: {
      id: 6,
      name: "Turkey Breast Sandwich",
      description: "Freshly baked bread filled with turkey breast and veggies.",
      price: 349,
      category: "Sandwiches",
      imageUrl: "https://th.bing.com/th/id/OIP.mLvwZmiFQiRIUjOJLdijowHaEK?w=293&h=180&c=7&r=0&o=5&pid=1.7",
      rating: 4.5,
    },
    averageRating: 4.4,
    deliveryTime: "25-35 mins",
  },
  {
    restaurantName: "Dairy Queen",
    location: "Various Locations",
    categories: ["Ice Cream", "Fast Food", "Burgers"],
    item: {
      id: 7,
      name: "Chicken Strip Basket",
      description: "Crispy chicken strips served with fries and gravy.",
      price: 399,
      imageUrl: "https://th.bing.com/th/id/OIP.Gwxv9g-p_jCw2E0EeMd82gHaEK?w=304&h=180&c=7&r=0&o=5&pid=1.7",
      category: "Burgers",
      rating: 3.8,
    },
    averageRating: 3.9,
    deliveryTime: "30-45 mins",
  },
  {
    restaurantName: "Wendy's",
    location: "Various Locations",
    categories: ["Burgers", "Salads", "Frostys"],
    item: {
      id: 8,
      name: "Baconator",
      description: "Two patties, two slices of cheese, and thick-cut bacon.",
      price: 579,
      category: "Burgers",
      imageUrl: "https://th.bing.com/th/id/OIP.m2m-kIsgqDWvmqm7B4jlGQHaE8?w=257&h=180&c=7&r=0&o=5&pid=1.7",
      rating: 3.5,
    },
    averageRating: 3.7,
    deliveryTime: "25-35 mins",
  },
  {
    restaurantName: "Panda Express",
    location: "Various Locations",
    categories: ["Chinese", "Fast Food"],
    item: {
      id: 9,
      name: "Orange Chicken",
      description: "Battered chicken in a sweet orange sauce.",
      price: 499,
      category: "Chinese",
      imageUrl: "https://th.bing.com/th/id/OIP.ZF_9R01X3kXaKbp3F5m-MAHaEK?w=296&h=180&c=7&r=0&o=5&pid=1.7",
      rating: 3.9,
    },
    averageRating: 3.8,
    deliveryTime: "20-30 mins",
  }
];

export default resList;

